# 비교연산자
 -  <     >     <=     >=    ==   !=
 -  결과는 논리값

In [ ]:
print(3>2)
print(3<2)
print(3==2)
print(3!=2)


True
False
False
True


# 논리 연산
 - and, or ,not

In [ ]:
print(True and True)
print(True or True)
print(not True)

True
True
False


# existance
- python에서 조건은 존재론(existance)적이다 => truthy,falsey

In [ ]:
# 0은 숫자가 없는 것고 같음 -> falsey
a =0.0
if a :
  print('Yes')
else :
  print('No')

No


In [ ]:
# None은 숫자가 없는 것고 같음 -> falsey
a = None
if a:
  print('Yes')
else:
  print('No')

No


In [ ]:
# 비어있는 dict 숫자가 없는 것고 같음 -> falsey
a ={}
if a:
  print('Yes')
else:
  print('No')

No


In [ ]:
a = int()
b = float()
c = list()
d = tuple()
e = str()
f = set()
g = frozenset()

if a:
  print('Yes')
else:
  print('No')

No


In [ ]:
3<2 or 4<5

True

In [ ]:
#and는 앞이 True이면 뒤에 값을 반환한다.
3 and 4

4

In [ ]:
3 and 0

0

In [ ]:
#and는 앞이 false이면 앞의 값을 반환한다.
0 and 3

0

In [ ]:
# and는 앞이 false이면 앞의 값을 반환한다.
# 비어 있는 문자열은없는 것과 같은 -> falsey
''and 4

''

In [ ]:
# or이면 앞의 True이면 앞의 값이 리턴된다.
1 or 4

1

In [ ]:
# or이면 앞의 false이면 뒤의 값이 리턴된다.
''or 4

4

#제어문(statement controller
- 문장의 흐름을 제어해 ㅜㄴ다
- 조건문 반복문
- 조건문   
 if~else
- 반복문   
 for ~ in   
 while
- break, countinue

In [ ]:
a = 8
if a>5 :
  print('OK')
else :
  print('Fail')

OK


```
if 조건식 :
  수행할 문장
else :
  수행할 문장
```


In [ ]:
a= 8
if 8%2==0 :
  print('even')
else :
  print('odd')

even


In [ ]:
# if a =4  이런식으로 if조건에 대입은 불가능함
name ='홍길동'
if name :
  print(name)

홍길동


In [ ]:
# 80이상이면 '상', 80미만 60이면'중' , 60미만이면 '하'
# 비교하는 대상이 같을땐 elif쓴다
a = 85
if a>=80 :
  print('상')
else :
  if a >= 60 :
    print('중')
  else :
    print('하')

a = 65
if a>=80 :
  print('상')
elif a >= 60 :
  print('중')
else :
  print('하')

상
중


In [ ]:
#비교하는 대상이 다를땐 if else 문안에 다른 if else문 사용
a = 85
if a>=60 :
 if a>= 80 :
  print('상')
 else :
  print('중')
else :
 print('하')

상


In [ ]:
member = True
grade ='A' #등급이 'S' 50, 'A' 30
point = 0

if member :
 # pass  # 값을 일단 지나가고 싶을때
 if grade == 'S' :
  point = 50
 else :
  point = 30
else :
  point = 0

print(point)

30


In [ ]:
#input을 이용한 if 문
age = int(input('나이:'))
gender = input('성별[남,여]')

if gender == '남' :
  if age >= 20 :
    print('성인 남성입니다')
  else :
    print('청소년 남성입니다')
elif gender == 여 :
  if age >= 20 :
    print('성인 여성입니다')
  else :
    print('청소년 여성입니다')
else :
  print('다시 입력해 주세요')





나이:20
성별[남,여]남
성인 남성입니다


* 퀴즈
1. 놀이기구에 키가 140cm이상이고,
  나이가 8세 이상인 사람만 탑승한다고 가정합니다.
2. 먼저 키(height)와 나이(age)를 입력받으세요.
3. 조건문 if~else를 사용하여 2개의 조건이 모두 참일 경우
  "놀이기구에 탑승할 수 있습니다."를 출력하세요.
4. 위 조건이 거짓일 경우 "놀이기구에 탑승할 수 없습니다."
    를 출력하세요.
5. 조건식과는 별개로 "오늘 하루 즐거운 시간되세요!"
   를 출력하세요.
'''

In [ ]:
#if 문에 연산자 사용가능
height = int(input('키:'))
age = int(input('나이:'))

if height >= 140 :
  if age >= 8 :
    print('놀이기구에 탑승할수 있습니다')
    print('오늘하루 즐거운 시간되세요!')
  else :
    print('놀이기구에 탑승할수 없습니다')
    print('오늘하루 즐거운 시간되세요!')
else :
  print('놀이기구에 탑승할수 없습니다')
  print('오늘하루 즐거운 시간되세요!')

키:120
나이:9
놀이기구에 탑승할수 없습니다
오늘하루 즐거운 시간되세요!


In [ ]:
#teacher
height = int(input('키:'))
age = int(input('나이:'))

if height >= 140 and age >= 8 :
    print('놀이기구에 탑승할수 있습니다')
else :
    print('놀이기구에 탑승할수 없습니다')

print('오늘하루 즐거운 시간되세요!')

키:100
나이:3
놀이기구에 탑승할수 없습니다
오늘하루 즐거운 시간되세요!


'''
[조건]
1. 18세 미만은 이 영화를 볼 수 없다
2. 18세 이상 59세 이하의 손님은 8000원
3. 60세 이상의 손님은 5000원
4. 포인트카드를 가지고 있고 지금까지 5편의 영화를 본 손님은 5000원

18세 미만이면 '티켓을 팔 수 없다'를 기술한 부분이다.
60세 이상이거나 포인트가 있고 5편 관람한 할인 대상자는 '티켓은 5000원입니다.
그외는 '티켓은 8000원입니다'로 출력하는 프로그램을 구현하시오.

[테스트1]
age=35
point_card =True
count=5

출력결과 : 티켓은 5000원입니다

[테스트2]
age=35
point_card =True
count=5

출력결과 : 티켓을 판매할 수 없습니다

[테스트3]
age=35
point_card =True
count=3

출력결과: 티켓은 8000원입니다
'''

In [ ]:
age = int(input('나이:'))
point = input('포인트 카드있으세요? [yes,no]')
time = int(input('관람횟수:'))
if point == yes or age < 18 and time >= 5:
  print('티켓을 판매할 수 없습니다')
elif point == yes or age <= 59 and time >= 5:
  print('티켓값은 8000원입니다')
else :
  print('티켓값은 5000원입니다')

나이:35
포인트 카드있으세요? [yes,no]yes
관람횟수:5


NameError: ignored

In [ ]:
age = int(input('나이:'))
point = input('포인트 카드있으세요? [yes,no]')
time = int(input('관람횟수:'))

if age >= 60 or point == yes :
  if point == yes and time >= 5 :
    print('티켓값은 5000원입니다')
  else :
    pass
elif age >= 18  :
    print('티켓값은 8000원입니다')
else :
    print('티켓을 판매할 수 없습니다')

나이:35
포인트 카드있으세요? [yes,no]yes
관람횟수:5
티켓값은 8000원입니다


In [ ]:
age = int(input('나이:'))
#point = input('포인트 카드있으세요? [yes,no]')
point_card = bool(input('포인트 소지여부'))
count = int(input('관람횟수:'))
1
if age <18 :
  print('영화를 볼수 없습니다')
elif age >=60 or (point_card and count==5)  :
  print('티켓값은 5000원입니다')
else :
  print('티켓값은 8000원입니다')

나이:35
포인트 소지여부no
관람횟수:5
티켓값은 5000원입니다


In [ ]:
# 윤년 : 연도를 4로 나누어 떨어지고 100으로 나누어 떨어지면 안되거나 400으로 나누어 떨어지면 된다
year = int(input('year:'))
month = int(input('month:'))
end_day_31 = [1,3,5,7,8,10,12]
end_day_30 = [4,6,9,11]
import sys
day = 28
check =''

#if month == end_day_31 :
  #day = 31
#elif month == end_day_30 :
  #day = 30
#else:
 # pass
if not(month>=1 and month<=12):
  print('월은 12월 까지만 입력해주세요')
  sys.exit()

#if month ==4 or month == 6 or month ==9 or month == 11:
if month in end_day_30:
  day =30
else :
  day = 31

if (year%4 ==0 and year%100!=0) or year%400==0 :
  check ='윤년'
  if month ==2 :
    day = 29
else :
  check ='평년'
  if month == 2:
    day = 28


print('{}년도는 {}월은 평년이고 마지막 일은 {}입니다.'.format(year,month,day))



year:2015
month:15
월은 12월 까지만 입력해주세요


SystemExit: ignored

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


##반복문 : while
반복문에서 else는 반복문이 완벽하게 끝났을때 실해된다
대부분의 프로그래밍 언어는 while과 for을 지원한다,   
else   
  - if - else
  - try - except - else fianlly
  -while - else
```
while 조건식 :
  수행할 문장
else :
  수행할 문장

```

In [ ]:
#while 문을 강제적으로 빠져나왔기 때문에 else 영역을 실행하지 않는다
#break는 반복문을 강제적으로 빠져나올때 사용한다 즉 반복문을 중단 한다
a = 10
while a>5:
  a-= 1 #a= a-1
  print(a)
else :
  print('end')

9
8
7
6
5
end


In [ ]:
a = 10
while a>5:
  a-= 1 #a= a-1
  print(a)
  if a==5:
    break
else :
  print('end')

9
8
7
6
5


In [ ]:
# continue 는 다음 차례 루프로 넘어간다
# 반복문을 중다나지 않음으로 else문이 실행된다
a = 10
while a>5 :
  a = a -1
  if a == 6:
    continue  # 반복문에서 continue를 만나면 무조건 조건식으로 간다 밑에꺼 재생x
  print(a)
else :
  print('end')


9
8
7
5
end


In [ ]:
# 1부터 10까지 출력하는 프로그램
a = 1
while a<=10 :
  print(a)
  a = a+1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#1부터 10까지 출력하는 프로그램을 구현하고 합계를 구하는 프로그램
#sum
a = 1
sum = 0
while a<=10 :
  print(a)
  sum = sum +a   #순서에 민감하다
  a = a+1

print('sum={}'.format(sum))

1
2
3
4
5
6
7
8
9
10
sum=55


In [ ]:
#1부터 10까지 짝수 홀수 합계 구하는 프로그램
#sum
a = 1
even = 0 #짝수
odd  = 0 #홀수
while a<=10 :

  if a%2==0:
    even = even + a
  else :
    odd = odd +a

  a = a+1


print('짝수={}'.format(even))
print('홀수={}'.format(odd))

짝수=30
홀수=25


```python
  for 변수 in iterable
    실행구문

```
```
for 문과 함께 사용되는함수
 for 변수 in range(시작번호 , 마지막번호 , 증감 값):
    실행구문

 for 변수 in enumerate(sequence, start):
    실행구문
  
 for 변수 in zip(data1, data2 ...)
    실행구문
```

##range

In [ ]:
#range(end)
for i in range(5): #0부터 5까지 1씩 증가(생략시) 0 1 2 3 4
  print(i)

In [ ]:
#range(start,end)
for i in range(1,5): #1부터 5미만의 값이 1씩증가  1 2 3 4
  print(i)

In [ ]:
#range(start,end,step)
for i in range(1,5,2): #1부터 5미만의 값이 2씩증가  1 3
  print(i)

### enumerate 함수
 - enumerate()함수는 인덱스와 객체를 동시에 저장할 수 있는 특징을 가진 for문을 좀더 효율적으로 사용하기 위한 함수이다.
 - enumerate()함수는 순서자료형(list, tuple, str)을 입력으로 받아 인덱스를 포함하는 enumerate 객체를 리턴한다.
 - enumerate([순서자료형], [시작값=0])의 형식을 가지며 순서자료형은 반복자가 가능한 객체가 입력도고 시작값은 입력시 해당수 부터 증가하며, 생략했을 경우 기본값은 0 이다.

In [ ]:
for k in enumerate(['appke','python','microsoft']):
  print(k)

(0, 'appke')
(1, 'python')
(2, 'microsoft')


In [ ]:
for k,v in enumerate(['appke','python','microsoft']):
  print(k,v)

0 appke
1 python
2 microsoft


In [ ]:
for k,v in enumerate(['appke','python','microsoft'],1):
  print(k,v)

1 appke
2 python
3 microsoft


In [ ]:
for k in enumerate({'one':10,'two':20}):
  print(k)

(0, 'one')
(1, 'two')


In [ ]:
a = {'one':10,'two':20}
for k,v in enumerate(a):
  print(k,a[v])

0 10
1 20


In [ ]:
for k,v in enumerate({10,20,30}):
  print(k,v)

0 10
1 20
2 30


### zip
- 매개인자로 여러 목록을 받아 각 목록의 요소를 튜플에 담아 목록에 저장한다.

In [ ]:
a =[1,2,3,4,5]
b=['a','b','c','d','e']

for x in zip(a,b):
  print(x)

(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')
(5, 'e')


In [ ]:
#list에 값 넣기
a =[]
for x in range(2,10):
  a.append(x)
print(a)

[2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#구구단
a =[]
for x in range(2,10) :
  for y in range(1,10) :
    print('{} X {}= {}'.format(x,y,x*y), end= '\t') # 줄맞추기
  print()

2 X 1= 2	2 X 2= 4	2 X 3= 6	2 X 4= 8	2 X 5= 10	2 X 6= 12	2 X 7= 14	2 X 8= 16	2 X 9= 18	
3 X 1= 3	3 X 2= 6	3 X 3= 9	3 X 4= 12	3 X 5= 15	3 X 6= 18	3 X 7= 21	3 X 8= 24	3 X 9= 27	
4 X 1= 4	4 X 2= 8	4 X 3= 12	4 X 4= 16	4 X 5= 20	4 X 6= 24	4 X 7= 28	4 X 8= 32	4 X 9= 36	
5 X 1= 5	5 X 2= 10	5 X 3= 15	5 X 4= 20	5 X 5= 25	5 X 6= 30	5 X 7= 35	5 X 8= 40	5 X 9= 45	
6 X 1= 6	6 X 2= 12	6 X 3= 18	6 X 4= 24	6 X 5= 30	6 X 6= 36	6 X 7= 42	6 X 8= 48	6 X 9= 54	
7 X 1= 7	7 X 2= 14	7 X 3= 21	7 X 4= 28	7 X 5= 35	7 X 6= 42	7 X 7= 49	7 X 8= 56	7 X 9= 63	
8 X 1= 8	8 X 2= 16	8 X 3= 24	8 X 4= 32	8 X 5= 40	8 X 6= 48	8 X 7= 56	8 X 8= 64	8 X 9= 72	
9 X 1= 9	9 X 2= 18	9 X 3= 27	9 X 4= 36	9 X 5= 45	9 X 6= 54	9 X 7= 63	9 X 8= 72	9 X 9= 81	


In [ ]:
a =[]
for x in range(2,10) :
  for y in range(1,10) :
    a.append(print('{} X {}= {}'.format(x,y,x*y))) # 줄맞추기
    a.append('\t')
  a.append('\t')
  print()

## Compression
- compression이란 interable한 오브젝트를 생성하기 위한 방법 중 하나이다
 - List Compression(LC)
 - Set Compression(SC)
 - Dict Compression(Dc)



## List Compression
- List 정의시 값을 정하지 않고 호출시 리스트 내의 값들이 처리되도록 구성
- A = [표현식 for 항목 in 반복 가능 객체(iterable)]
- A = [표현식 for 항목 in 반복 가능 객체(iterable) if 논리식]
- A = [표현식 for 항목 in 반복 가능 객체(iterable)1 for 항목2 in 반복 가능 객체(iterable)2 if 논리식 ]

In [ ]:
#제곱
s = []
for x in range(10) :
  s.append(x**2)
print(s)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
s = [x**2 for x in range(10)]
print(s)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
s = [x**2 for x in range(10) if x% 2==0]
print(s)

[0, 4, 16, 36, 64]


In [ ]:
s =[]
for i in range(1,3):
  for j in range(4,8):
    print('{}{}'.format(i,j))
    s.append((i,j))
print(s)

14
15
16
17
24
25
26
27
[(1, 4), (1, 5), (1, 6), (1, 7), (2, 4), (2, 5), (2, 6), (2, 7)]


In [ ]:
s =[(i,j) for i in range(1,3) for j in range(4,8)]
print(s)

[(1, 4), (1, 5), (1, 6), (1, 7), (2, 4), (2, 5), (2, 6), (2, 7)]


총 판매금액을 구하는 프로그램(list comprehension을 사용)   
cnt = [1,1,2,1]   
prod = [500,1000,400,6000]

In [ ]:

s = []
cnt = [1,1,2,1]
prod = [500,1000,400,600]
for i,j in zip(cnt,prod):
  s.append(i*j)

print(sum(s))

2900


In [ ]:

cnt = [1,1,2,1]
prod = [500,1000,400,600]
s = sum([i*j for i,j in zip(cnt,prod)])
print(s)

2900


'e'가 포함되어 있는 과일들만 추출해서 대문자로 출력하는 프로그램을 구현하세요.   
fruits = ['apple', 'banana', 'cherry', 'grape', 'kiwi', 'tomato']

[출력결과]
['APPLE', 'CHERRY', 'GRAPE']

In [ ]:
fruits = ['apple', 'banana', 'cherry', 'grape', 'kiwi', 'tomato']
s = [ item.upper() for item in fruits if 'e' in item.lower()]
print(s)

['APPLE', 'CHERRY', 'GRAPE']


### dict comprehension
- 사전 정의시 값을 정하지 않고 호출시 사전 내의 값들이 처리되도록 구성
- A = {표현식for(k,v) in 반복 가능 객체 if 논리식}

In [ ]:
d = {}
for k,v in zip(range(9),range(9)) :
  d[k]=v
print(d)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}


In [ ]:
d = { k:v for k,v in zip(range(9),range(9))}
d

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}

In [ ]:
a = {'x':1,'y':2,'z':3}
b = {'w':10,'x':11,'y':2}
print(a.keys())
print(b.keys())
c = a.keys() - b.keys()
print(c)
d = c.pop()
print('{}:{}'.format(d,a[d]))  # pop은 완전히 꺼내오는거라 2번 불가능 # 변수에 따로 c.pop()

dict_keys(['x', 'y', 'z'])
dict_keys(['w', 'x', 'y'])
{'z'}
z:3


In [ ]:
a = {'x':1,'y':2,'z':3}
b = {'w':10,'x':11,'y':2}
k = {key:a[key] for key in a.keys() - b.keys()}
print(k)

{'z': 3}


### set comprehension
- Set 정의시 값을 정하지 않고 호출시 Set내의 닶들이 처리되도록 구성
- A = {표현식 for 항목 in 반복가능 객체 if 논리식}


In [ ]:
k ={ (i,j) for i in range(1,3) for j in range(4,8)} #튜플로 묶어서 call
print(k)

{(2, 4), (2, 7), (1, 5), (1, 4), (1, 7), (2, 6), (1, 6), (2, 5)}


[문제1]  
리스트에 저장된 문자열 중에서 길이가 5인 것들만 리스트 형태로 출력하도록 구현하세요.  

a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']  

[출력결과]     
['alpha', 'bravo', 'delta', 'hotel', 'india']

In [ ]:
a= ['alpha', 'bravo', 'charlie', 'delta', 'echo', 'foxtrot', 'golf', 'hotel', 'india']
b=[]
#b= a.pop(d)
#c=len(b)
#print(c)
for d in a :
  if len(d) == 5:
    b.append(d)
print(b)
#[[print(d)] for d in a if len(d) == 5 ]

['alpha', 'bravo', 'delta', 'hotel', 'india']


[문제2]    
가로 크기를 저장한 리스트를 활용해서 가로 크기가 불규칙한  리스트를 생성하도록 프로그램을 구현하세요.

a = [3, 1,3, 2, 5]  


[출력결과]  
[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]


In [ ]:
a = [3, 1,3, 2, 5]
for i in a :
  print([[0]*i], end='')

[[0, 0, 0]][[0]][[0, 0, 0]][[0, 0]][[0, 0, 0, 0, 0]]

[문제3]    
포트폴리오의 총 비용을 계산하는 프로그램을 구현하세요.   

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]     

[출력결과]  
44671.15

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
for a in portfolio :
  b = (a['shares'] *a['price'])

  print(sum([b]))




TypeError: ignored

[문제4]  
포트폴리오에서 100주 이상 보유한 종목의 리스트를 출력하는 프로그램을 구현하세요.    
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  


[출력결과]    
[{'name': 'AA', 'shares': 100, 'price': 32.2},
 {'name': 'CAT', 'shares': 150, 'price': 83.44},
 {'name': 'MSFT', 'shares': 200, 'price': 51.23},
 {'name': 'IBM', 'shares': 100, 'price': 70.44}]


In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]
for a in portfolio :
  if a['shares'] >= 100 :
    print(a)

{'name': 'AA', 'shares': 100, 'price': 32.2}
{'name': 'CAT', 'shares': 150, 'price': 83.44}
{'name': 'MSFT', 'shares': 200, 'price': 51.23}
{'name': 'IBM', 'shares': 100, 'price': 70.44}


[문제5]

보유한 MSFT와 IBM주식 전체 리스트를 출력하는 프로그램을 구현하세요.  

portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]  

[출력결과]   
[{'name': 'IBM', 'price': 91.1, 'shares': 50},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200},
 {'name': 'MSFT', 'price': 65.1, 'shares': 50},
 {'name': 'IBM', 'price': 70.44, 'shares': 100}]  



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

for a in portfolio :
  if a['name'] in {'MSFT','IBM'} :
    print([a])







[{'name': 'IBM', 'shares': 50, 'price': 91.1}]
[{'name': 'MSFT', 'shares': 200, 'price': 51.23}]
[{'name': 'MSFT', 'shares': 50, 'price': 65.1}]
[{'name': 'IBM', 'shares': 100, 'price': 70.44}]


[문제6]
보유 종목 중 가격이 10,000달러가 넘는 것의 리스트를 구현하는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]    
[{'name': 'CAT', 'price': 83.44, 'shares': 150},
 {'name': 'MSFT', 'price': 51.23, 'shares': 200}]

In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

for a in portfolio :
  if a['price']*a['shares'] > 10000 :
    print(a)


{'name': 'CAT', 'shares': 150, 'price': 83.44}
{'name': 'MSFT', 'shares': 200, 'price': 51.23}


[문제7]   
portfolio에서 얻은 name과 shares를 가지고 튜플의 리스트 (name, shares)를 만드는 프로그램을 구현하세요.  
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

[출력결과]   
[('AA', 100),
 ('IBM', 50),
 ('CAT', 150),
 ('MSFT', 200),
 ('GE', 95),
 ('MSFT', 50),
 ('IBM', 100)]



In [ ]:
portfolio = [{'name':'AA', 'shares':100, 'price':32.20},{'name':'IBM', 'shares':50, 'price':91.10},{'name':'CAT', 'shares':150, 'price':83.44},{'name':'MSFT', 'shares':200, 'price':51.23},{'name':'GE', 'shares':95, 'price':40.37},{'name':'MSFT', 'shares':50, 'price':65.10},{'name':'IBM', 'shares':100, 'price':70.44} ]

for a in portfolio :
  print([(a['name'], a['shares'])],end ='')

[('AA', 100)][('IBM', 50)][('CAT', 150)][('MSFT', 200)][('GE', 95)][('MSFT', 50)][('IBM', 100)]

[문제8]  

리스트에서 int만 추출하여 프로그램을 구현하세요.  
oldlist = [1, 2, 'A', False, 3]


[출력결과]   
[1, 2, 3]  


In [ ]:
oldlist = [1, 2, 'A', False, 3]
for a in oldlist :
  if type(a)==int :

    print(a)


1
4
9


[문제9]   
1부터 10까지의 홀수, 짝수로 출력하는 프로그램을 구현하세요.

[출력결과]   
{1: '홀수',
 2: '짝수',
 3: '홀수',
 4: '짝수',
 5: '홀수',
 6: '짝수',
 7: '홀수',
 8: '짝수',
 9: '홀수',
 10: '짝수'}


In [ ]:
for n in range(1, 11) :
  if n%2==0 :
    print('짝수',end='')
  else :
    print('홀수',end='')

홀수짝수홀수짝수홀수짝수홀수짝수홀수짝수